dist: xenial
language: java
jdk:
  - oraclejdk11
  - oraclejdk12
  - oraclejdk13
  - oraclejdk14
  - oraclejdk15
  - openjdk11
  - openjdk12
  - openjdk13
  - openjdk14
  - openjdk15
notifications:
  email: false