grammar function;

methodInvocation: IDENTIFIER '(' PARAMETERS ')';

PARAMETERS: PARAMETER ( ',' PARAMETER )* ;
PARAMETER: FRACTION | INTEGER | STRING | NULL;

FRACTION: INTEGER '/' INTEGER;

STRING: SINGLE_QUOTED_STRING | DOUBLE_QUOTED_STRING;
SINGLE_QUOTED_STRING:  '\'' (~["'"])* '\'';
DOUBLE_QUOTED_STRING: '"' (~["'"])* '"';

IDENTIFIER: LETTER (LETTER | DIGIT)*;
LETTER: [a];
DIGIT: [0];

INTEGER: [0-9]+;
NULL : 'null';
